services:
  ### Broker #1
  kafka1:
    image: apache/kafka:3.9.1
    container_name: kafka1
    hostname: kafka1
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "CONTROLLER://:9093,PLAINTEXT://:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://221.144.36.127:9092,CONTROLLER://kafka1:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - kt-net

  ### Broker #2
  kafka2:
    image: apache/kafka:3.9.1
    container_name: kafka2
    hostname: kafka2
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "2"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "CONTROLLER://:9093,PLAINTEXT://:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://221.144.36.127:9192,CONTROLLER://kafka2:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
    ports:
      - "9192:9092"
      - "9193:9093"
    networks:
      - kt-net

  ### Broker #3
  kafka3:
    image: apache/kafka:3.9.1
    container_name: kafka3
    hostname: kafka3
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "3"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "CONTROLLER://:9093,PLAINTEXT://:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://221.144.36.127:9292,CONTROLLER://kafka3:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
    ports:
      - "9292:9092"
      - "9293:9093"
    networks:
      - kt-net

  ### Python 변환 서비스
  transform:
    build: ./transform
    container_name: transformer
    restart: on-failure
    environment:
      BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      RAW_TOPIC: "raw-logs"
      OCSF_TOPIC: "ocsf-logs"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kt-net

networks:
  kt-net:
